[tool.poetry]
name = "telegram-bili-feed-helper"
version = "0.1.0"
description = ""
authors = ["simonsmh"]
license = "GPLv3"
readme = "README.md"
packages = [{ include = "biliparser" }]

[tool.poetry.dependencies]
python = "^3.13"
aiomysql = "^0.2.0"
asyncpg = "^0.30.0"
beautifulsoup4 = "^4.12.3"
httpx = {extras = ["http2"], version = "^0.27.2"}
loguru = "^0.7.2"
lxml = "^5.3.0"
pillow = "^10.3.0"
python-telegram-bot = {extras = ["all"], version = "^21.6"}
redis = "^5.1.1"
telegraph = {extras = ["aio"], version = "^2.2.0"}
tortoise-orm = {extras = ["accel"], version = "^0.21.7"}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-asyncio = "^0.23.8"

[tool.poetry.scripts]
bilifeedbot = "biliparser.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
