name: Deploy to Fly
on:
  workflow_dispatch:
#  workflow_run:
#    workflows: [Create and publish a Docker image]
#    types: [completed]

jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@main
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
